name: n8n Sync

on:
  push:
    branches: ["main"]
    paths:
      - "workflows/**"
      - ".github/workflows/n8n-sync.yml"
      - "scripts/**"
  workflow_dispatch: {}

jobs:
  sync-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Sync workflows via Public API
        run: |
          node scripts/sync-workflows.mjs
        env:
          N8N_BASE_URL: ${{ secrets.N8N_BASE_URL }}
          N8N_API_KEY: ${{ secrets.N8N_API_KEY }}
